#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# BV-BRC documentation build configuration file, created by
# sphinx-quickstart on Tue Oct 10 11:57:26 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import sys  # used by the spelling-builder guard below


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['myst_parser', 'sphinxcontrib.newsfeed', 'sphinxcontrib.httpdomain']
#extensions = ['recommonmark', 'sphinxcontrib.newsfeed', 'sphinxcontrib.spelling', 'sphinxcontrib.httpdomain']

# sphinxcontrib.spelling is loaded only when the native `enchant` C library is present.
#
# pyenchant is a thin ctypes wrapper: importing it fails outright when libenchant is not
# installed, and because a Sphinx extension is imported at config time that failure killed
# `make html` entirely -- a spell checker that `make html` never runs was breaking the
# ordinary HTML build for anyone who had not also `brew install enchant` /
# `apt install libenchant-2-2`. Now the HTML build works everywhere and the spelling
# builder stays available to whoever has the library. CI installs it, so `-b spelling`
# remains covered there.
try:
    import enchant  # noqa: F401  (imported for the side effect of locating libenchant)
except ImportError:
    spelling_available = False
else:
    spelling_available = True
    extensions.append('sphinxcontrib.spelling')

myst_heading_anchors = 2

# spelling check extension (settings are inert unless the extension loaded above)
spelling_lang='en_US'
spelling_word_list_filename='spelling_wordlist.txt'
spelling_show_suggestions=False

# Fail loudly rather than silently skipping the check: without this, `-b spelling` on a
# machine lacking libenchant would report only an opaque "builder not registered" error.
if not spelling_available and 'spelling' in sys.argv:
    raise RuntimeError(
        "The 'spelling' builder needs the native enchant library, which is not installed.\n"
        "  macOS:         brew install enchant\n"
        "  Ubuntu/Debian: sudo apt install libenchant-2-2\n"
        "Plain `make html` does not need it."
    )

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'dxkb'
copyright = '2026 | The dxkb Team'
author = 'The dxkb Team'


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ''
# The full version, including alpha/beta/rc tags.
release = ''

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_options = {
    'logo_only': True,
    'collapse_navigation': True,
    'display_version': True,
    'style_nav_header_background': '#e3e3e3'
}
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_logo = ""
html_favicon = "_static/favicon.ico"
html_title = "dxkb"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# A list of paths that contain extra files not directly relation to the docs
# Relative paths to the config.py file
# Copied directly to the output directly (_build/html)
html_extra_path = [''] # Inherited from bvbrc_web


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'BVBRCdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'BV-BRC.tex', 'BV-BRC Documentation',
     'BV-BRC team', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'bvbrc', 'BV-BRC Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'BV-BRC', 'BV-BRC Documentation',
     author, 'BV-BRC', 'One line description of project.',
     'Miscellaneous'),
]




#
# Workaround for warnings seen on build
# cf https://github.com/mitre/fieldmanual/pull/37
#

from recommonmark.parser import CommonMarkParser
def visit_document(*_):
     pass


# Removes irrelevant warning messages during md file parsing.
# REF: https://github.com/readthedocs/recommonmark/issues/177
# Hopefully will be unnecessary in the future (when recommonmark > 0.6.0 exists)
setattr(CommonMarkParser, 'visit_document', visit_document)

